"""\nAtlas Intelligent Gateway Routing Policies & Latency SLA Balancers.\nImplements rule-based routing, intent classification, and cost optimization algorithms.\n"""\n
from typing import Dict, Any, List, Optional, Tuple\n
ROUTING_POLICIES_CATALOG: Dict[str, Dict[str, Any]] = {
    "policy_coding_v1": {
        "intent": "coding",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 175,
        "max_cost_per_query_usd": 0.015,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_coding_v2": {
        "intent": "coding",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 200,
        "max_cost_per_query_usd": 0.02,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_coding_v3": {
        "intent": "coding",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 225,
        "max_cost_per_query_usd": 0.025,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_coding_v4": {
        "intent": "coding",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 250,
        "max_cost_per_query_usd": 0.03,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_coding_v5": {
        "intent": "coding",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 275,
        "max_cost_per_query_usd": 0.035,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_coding_v6": {
        "intent": "coding",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 300,
        "max_cost_per_query_usd": 0.04,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_coding_v7": {
        "intent": "coding",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 325,
        "max_cost_per_query_usd": 0.045000000000000005,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_coding_v8": {
        "intent": "coding",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 350,
        "max_cost_per_query_usd": 0.05,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_coding_v9": {
        "intent": "coding",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 375,
        "max_cost_per_query_usd": 0.055,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_coding_v10": {
        "intent": "coding",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 400,
        "max_cost_per_query_usd": 0.060000000000000005,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_coding_v11": {
        "intent": "coding",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 425,
        "max_cost_per_query_usd": 0.065,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_coding_v12": {
        "intent": "coding",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 450,
        "max_cost_per_query_usd": 0.06999999999999999,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_coding_v13": {
        "intent": "coding",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 475,
        "max_cost_per_query_usd": 0.075,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_coding_v14": {
        "intent": "coding",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 500,
        "max_cost_per_query_usd": 0.08,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_coding_v15": {
        "intent": "coding",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 525,
        "max_cost_per_query_usd": 0.08499999999999999,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_coding_v16": {
        "intent": "coding",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 550,
        "max_cost_per_query_usd": 0.09,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_coding_v17": {
        "intent": "coding",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 575,
        "max_cost_per_query_usd": 0.095,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_coding_v18": {
        "intent": "coding",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 600,
        "max_cost_per_query_usd": 0.09999999999999999,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_coding_v19": {
        "intent": "coding",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 625,
        "max_cost_per_query_usd": 0.105,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_reasoning_v1": {
        "intent": "reasoning",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 175,
        "max_cost_per_query_usd": 0.015,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_reasoning_v2": {
        "intent": "reasoning",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 200,
        "max_cost_per_query_usd": 0.02,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_reasoning_v3": {
        "intent": "reasoning",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 225,
        "max_cost_per_query_usd": 0.025,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_reasoning_v4": {
        "intent": "reasoning",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 250,
        "max_cost_per_query_usd": 0.03,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_reasoning_v5": {
        "intent": "reasoning",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 275,
        "max_cost_per_query_usd": 0.035,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_reasoning_v6": {
        "intent": "reasoning",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 300,
        "max_cost_per_query_usd": 0.04,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_reasoning_v7": {
        "intent": "reasoning",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 325,
        "max_cost_per_query_usd": 0.045000000000000005,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_reasoning_v8": {
        "intent": "reasoning",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 350,
        "max_cost_per_query_usd": 0.05,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_reasoning_v9": {
        "intent": "reasoning",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 375,
        "max_cost_per_query_usd": 0.055,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_reasoning_v10": {
        "intent": "reasoning",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 400,
        "max_cost_per_query_usd": 0.060000000000000005,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_reasoning_v11": {
        "intent": "reasoning",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 425,
        "max_cost_per_query_usd": 0.065,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_reasoning_v12": {
        "intent": "reasoning",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 450,
        "max_cost_per_query_usd": 0.06999999999999999,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_reasoning_v13": {
        "intent": "reasoning",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 475,
        "max_cost_per_query_usd": 0.075,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_reasoning_v14": {
        "intent": "reasoning",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 500,
        "max_cost_per_query_usd": 0.08,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_reasoning_v15": {
        "intent": "reasoning",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 525,
        "max_cost_per_query_usd": 0.08499999999999999,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_reasoning_v16": {
        "intent": "reasoning",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 550,
        "max_cost_per_query_usd": 0.09,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_reasoning_v17": {
        "intent": "reasoning",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 575,
        "max_cost_per_query_usd": 0.095,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_reasoning_v18": {
        "intent": "reasoning",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 600,
        "max_cost_per_query_usd": 0.09999999999999999,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_reasoning_v19": {
        "intent": "reasoning",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 625,
        "max_cost_per_query_usd": 0.105,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_fast_chat_v1": {
        "intent": "fast_chat",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 175,
        "max_cost_per_query_usd": 0.015,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_fast_chat_v2": {
        "intent": "fast_chat",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 200,
        "max_cost_per_query_usd": 0.02,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_fast_chat_v3": {
        "intent": "fast_chat",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 225,
        "max_cost_per_query_usd": 0.025,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_fast_chat_v4": {
        "intent": "fast_chat",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 250,
        "max_cost_per_query_usd": 0.03,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_fast_chat_v5": {
        "intent": "fast_chat",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 275,
        "max_cost_per_query_usd": 0.035,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_fast_chat_v6": {
        "intent": "fast_chat",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 300,
        "max_cost_per_query_usd": 0.04,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_fast_chat_v7": {
        "intent": "fast_chat",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 325,
        "max_cost_per_query_usd": 0.045000000000000005,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_fast_chat_v8": {
        "intent": "fast_chat",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 350,
        "max_cost_per_query_usd": 0.05,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_fast_chat_v9": {
        "intent": "fast_chat",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 375,
        "max_cost_per_query_usd": 0.055,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_fast_chat_v10": {
        "intent": "fast_chat",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 400,
        "max_cost_per_query_usd": 0.060000000000000005,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_fast_chat_v11": {
        "intent": "fast_chat",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 425,
        "max_cost_per_query_usd": 0.065,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_fast_chat_v12": {
        "intent": "fast_chat",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 450,
        "max_cost_per_query_usd": 0.06999999999999999,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_fast_chat_v13": {
        "intent": "fast_chat",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 475,
        "max_cost_per_query_usd": 0.075,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_fast_chat_v14": {
        "intent": "fast_chat",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 500,
        "max_cost_per_query_usd": 0.08,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_fast_chat_v15": {
        "intent": "fast_chat",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 525,
        "max_cost_per_query_usd": 0.08499999999999999,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_fast_chat_v16": {
        "intent": "fast_chat",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 550,
        "max_cost_per_query_usd": 0.09,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_fast_chat_v17": {
        "intent": "fast_chat",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 575,
        "max_cost_per_query_usd": 0.095,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_fast_chat_v18": {
        "intent": "fast_chat",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 600,
        "max_cost_per_query_usd": 0.09999999999999999,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_fast_chat_v19": {
        "intent": "fast_chat",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 625,
        "max_cost_per_query_usd": 0.105,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_summarization_v1": {
        "intent": "summarization",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 175,
        "max_cost_per_query_usd": 0.015,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_summarization_v2": {
        "intent": "summarization",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 200,
        "max_cost_per_query_usd": 0.02,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_summarization_v3": {
        "intent": "summarization",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 225,
        "max_cost_per_query_usd": 0.025,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_summarization_v4": {
        "intent": "summarization",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 250,
        "max_cost_per_query_usd": 0.03,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_summarization_v5": {
        "intent": "summarization",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 275,
        "max_cost_per_query_usd": 0.035,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_summarization_v6": {
        "intent": "summarization",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 300,
        "max_cost_per_query_usd": 0.04,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_summarization_v7": {
        "intent": "summarization",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 325,
        "max_cost_per_query_usd": 0.045000000000000005,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_summarization_v8": {
        "intent": "summarization",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 350,
        "max_cost_per_query_usd": 0.05,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_summarization_v9": {
        "intent": "summarization",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 375,
        "max_cost_per_query_usd": 0.055,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_summarization_v10": {
        "intent": "summarization",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 400,
        "max_cost_per_query_usd": 0.060000000000000005,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_summarization_v11": {
        "intent": "summarization",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 425,
        "max_cost_per_query_usd": 0.065,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_summarization_v12": {
        "intent": "summarization",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 450,
        "max_cost_per_query_usd": 0.06999999999999999,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_summarization_v13": {
        "intent": "summarization",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 475,
        "max_cost_per_query_usd": 0.075,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_summarization_v14": {
        "intent": "summarization",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 500,
        "max_cost_per_query_usd": 0.08,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_summarization_v15": {
        "intent": "summarization",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 525,
        "max_cost_per_query_usd": 0.08499999999999999,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_summarization_v16": {
        "intent": "summarization",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 550,
        "max_cost_per_query_usd": 0.09,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_summarization_v17": {
        "intent": "summarization",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 575,
        "max_cost_per_query_usd": 0.095,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_summarization_v18": {
        "intent": "summarization",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 600,
        "max_cost_per_query_usd": 0.09999999999999999,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_summarization_v19": {
        "intent": "summarization",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 625,
        "max_cost_per_query_usd": 0.105,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_extraction_v1": {
        "intent": "extraction",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 175,
        "max_cost_per_query_usd": 0.015,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_extraction_v2": {
        "intent": "extraction",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 200,
        "max_cost_per_query_usd": 0.02,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_extraction_v3": {
        "intent": "extraction",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 225,
        "max_cost_per_query_usd": 0.025,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_extraction_v4": {
        "intent": "extraction",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 250,
        "max_cost_per_query_usd": 0.03,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_extraction_v5": {
        "intent": "extraction",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 275,
        "max_cost_per_query_usd": 0.035,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_extraction_v6": {
        "intent": "extraction",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 300,
        "max_cost_per_query_usd": 0.04,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_extraction_v7": {
        "intent": "extraction",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 325,
        "max_cost_per_query_usd": 0.045000000000000005,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_extraction_v8": {
        "intent": "extraction",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 350,
        "max_cost_per_query_usd": 0.05,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_extraction_v9": {
        "intent": "extraction",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 375,
        "max_cost_per_query_usd": 0.055,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_extraction_v10": {
        "intent": "extraction",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 400,
        "max_cost_per_query_usd": 0.060000000000000005,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_extraction_v11": {
        "intent": "extraction",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 425,
        "max_cost_per_query_usd": 0.065,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_extraction_v12": {
        "intent": "extraction",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 450,
        "max_cost_per_query_usd": 0.06999999999999999,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_extraction_v13": {
        "intent": "extraction",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 475,
        "max_cost_per_query_usd": 0.075,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_extraction_v14": {
        "intent": "extraction",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 500,
        "max_cost_per_query_usd": 0.08,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_extraction_v15": {
        "intent": "extraction",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 525,
        "max_cost_per_query_usd": 0.08499999999999999,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_extraction_v16": {
        "intent": "extraction",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 550,
        "max_cost_per_query_usd": 0.09,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_extraction_v17": {
        "intent": "extraction",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 575,
        "max_cost_per_query_usd": 0.095,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_extraction_v18": {
        "intent": "extraction",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 600,
        "max_cost_per_query_usd": 0.09999999999999999,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_extraction_v19": {
        "intent": "extraction",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 625,
        "max_cost_per_query_usd": 0.105,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_creative_v1": {
        "intent": "creative",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 175,
        "max_cost_per_query_usd": 0.015,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_creative_v2": {
        "intent": "creative",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 200,
        "max_cost_per_query_usd": 0.02,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_creative_v3": {
        "intent": "creative",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 225,
        "max_cost_per_query_usd": 0.025,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_creative_v4": {
        "intent": "creative",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 250,
        "max_cost_per_query_usd": 0.03,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_creative_v5": {
        "intent": "creative",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 275,
        "max_cost_per_query_usd": 0.035,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_creative_v6": {
        "intent": "creative",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 300,
        "max_cost_per_query_usd": 0.04,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_creative_v7": {
        "intent": "creative",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 325,
        "max_cost_per_query_usd": 0.045000000000000005,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_creative_v8": {
        "intent": "creative",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 350,
        "max_cost_per_query_usd": 0.05,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_creative_v9": {
        "intent": "creative",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 375,
        "max_cost_per_query_usd": 0.055,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_creative_v10": {
        "intent": "creative",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 400,
        "max_cost_per_query_usd": 0.060000000000000005,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_creative_v11": {
        "intent": "creative",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 425,
        "max_cost_per_query_usd": 0.065,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_creative_v12": {
        "intent": "creative",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 450,
        "max_cost_per_query_usd": 0.06999999999999999,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_creative_v13": {
        "intent": "creative",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 475,
        "max_cost_per_query_usd": 0.075,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_creative_v14": {
        "intent": "creative",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 500,
        "max_cost_per_query_usd": 0.08,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_creative_v15": {
        "intent": "creative",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 525,
        "max_cost_per_query_usd": 0.08499999999999999,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_creative_v16": {
        "intent": "creative",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 550,
        "max_cost_per_query_usd": 0.09,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_creative_v17": {
        "intent": "creative",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 575,
        "max_cost_per_query_usd": 0.095,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_creative_v18": {
        "intent": "creative",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 600,
        "max_cost_per_query_usd": 0.09999999999999999,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_creative_v19": {
        "intent": "creative",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 625,
        "max_cost_per_query_usd": 0.105,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_vision_v1": {
        "intent": "vision",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 175,
        "max_cost_per_query_usd": 0.015,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_vision_v2": {
        "intent": "vision",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 200,
        "max_cost_per_query_usd": 0.02,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_vision_v3": {
        "intent": "vision",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 225,
        "max_cost_per_query_usd": 0.025,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_vision_v4": {
        "intent": "vision",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 250,
        "max_cost_per_query_usd": 0.03,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_vision_v5": {
        "intent": "vision",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 275,
        "max_cost_per_query_usd": 0.035,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_vision_v6": {
        "intent": "vision",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 300,
        "max_cost_per_query_usd": 0.04,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_vision_v7": {
        "intent": "vision",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 325,
        "max_cost_per_query_usd": 0.045000000000000005,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_vision_v8": {
        "intent": "vision",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 350,
        "max_cost_per_query_usd": 0.05,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_vision_v9": {
        "intent": "vision",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 375,
        "max_cost_per_query_usd": 0.055,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_vision_v10": {
        "intent": "vision",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 400,
        "max_cost_per_query_usd": 0.060000000000000005,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_vision_v11": {
        "intent": "vision",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 425,
        "max_cost_per_query_usd": 0.065,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_vision_v12": {
        "intent": "vision",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 450,
        "max_cost_per_query_usd": 0.06999999999999999,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_vision_v13": {
        "intent": "vision",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 475,
        "max_cost_per_query_usd": 0.075,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_vision_v14": {
        "intent": "vision",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 500,
        "max_cost_per_query_usd": 0.08,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_vision_v15": {
        "intent": "vision",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 525,
        "max_cost_per_query_usd": 0.08499999999999999,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_vision_v16": {
        "intent": "vision",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 550,
        "max_cost_per_query_usd": 0.09,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_vision_v17": {
        "intent": "vision",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 575,
        "max_cost_per_query_usd": 0.095,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_vision_v18": {
        "intent": "vision",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 600,
        "max_cost_per_query_usd": 0.09999999999999999,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_vision_v19": {
        "intent": "vision",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 625,
        "max_cost_per_query_usd": 0.105,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_audio_v1": {
        "intent": "audio",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 175,
        "max_cost_per_query_usd": 0.015,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_audio_v2": {
        "intent": "audio",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 200,
        "max_cost_per_query_usd": 0.02,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_audio_v3": {
        "intent": "audio",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 225,
        "max_cost_per_query_usd": 0.025,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_audio_v4": {
        "intent": "audio",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 250,
        "max_cost_per_query_usd": 0.03,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_audio_v5": {
        "intent": "audio",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 275,
        "max_cost_per_query_usd": 0.035,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_audio_v6": {
        "intent": "audio",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 300,
        "max_cost_per_query_usd": 0.04,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_audio_v7": {
        "intent": "audio",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 325,
        "max_cost_per_query_usd": 0.045000000000000005,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_audio_v8": {
        "intent": "audio",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 350,
        "max_cost_per_query_usd": 0.05,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_audio_v9": {
        "intent": "audio",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 375,
        "max_cost_per_query_usd": 0.055,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_audio_v10": {
        "intent": "audio",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 400,
        "max_cost_per_query_usd": 0.060000000000000005,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_audio_v11": {
        "intent": "audio",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 425,
        "max_cost_per_query_usd": 0.065,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_audio_v12": {
        "intent": "audio",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 450,
        "max_cost_per_query_usd": 0.06999999999999999,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_audio_v13": {
        "intent": "audio",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 475,
        "max_cost_per_query_usd": 0.075,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_audio_v14": {
        "intent": "audio",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 500,
        "max_cost_per_query_usd": 0.08,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_audio_v15": {
        "intent": "audio",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 525,
        "max_cost_per_query_usd": 0.08499999999999999,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_audio_v16": {
        "intent": "audio",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 550,
        "max_cost_per_query_usd": 0.09,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_audio_v17": {
        "intent": "audio",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 575,
        "max_cost_per_query_usd": 0.095,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_audio_v18": {
        "intent": "audio",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 600,
        "max_cost_per_query_usd": 0.09999999999999999,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_audio_v19": {
        "intent": "audio",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 625,
        "max_cost_per_query_usd": 0.105,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_high_throughput_v1": {
        "intent": "high_throughput",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 175,
        "max_cost_per_query_usd": 0.015,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_high_throughput_v2": {
        "intent": "high_throughput",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 200,
        "max_cost_per_query_usd": 0.02,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_high_throughput_v3": {
        "intent": "high_throughput",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 225,
        "max_cost_per_query_usd": 0.025,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_high_throughput_v4": {
        "intent": "high_throughput",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 250,
        "max_cost_per_query_usd": 0.03,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_high_throughput_v5": {
        "intent": "high_throughput",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 275,
        "max_cost_per_query_usd": 0.035,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_high_throughput_v6": {
        "intent": "high_throughput",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 300,
        "max_cost_per_query_usd": 0.04,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_high_throughput_v7": {
        "intent": "high_throughput",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 325,
        "max_cost_per_query_usd": 0.045000000000000005,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_high_throughput_v8": {
        "intent": "high_throughput",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 350,
        "max_cost_per_query_usd": 0.05,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_high_throughput_v9": {
        "intent": "high_throughput",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 375,
        "max_cost_per_query_usd": 0.055,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_high_throughput_v10": {
        "intent": "high_throughput",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 400,
        "max_cost_per_query_usd": 0.060000000000000005,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_high_throughput_v11": {
        "intent": "high_throughput",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 425,
        "max_cost_per_query_usd": 0.065,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_high_throughput_v12": {
        "intent": "high_throughput",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 450,
        "max_cost_per_query_usd": 0.06999999999999999,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_high_throughput_v13": {
        "intent": "high_throughput",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 475,
        "max_cost_per_query_usd": 0.075,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_high_throughput_v14": {
        "intent": "high_throughput",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 500,
        "max_cost_per_query_usd": 0.08,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_high_throughput_v15": {
        "intent": "high_throughput",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 525,
        "max_cost_per_query_usd": 0.08499999999999999,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_high_throughput_v16": {
        "intent": "high_throughput",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 550,
        "max_cost_per_query_usd": 0.09,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_high_throughput_v17": {
        "intent": "high_throughput",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 575,
        "max_cost_per_query_usd": 0.095,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_high_throughput_v18": {
        "intent": "high_throughput",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 600,
        "max_cost_per_query_usd": 0.09999999999999999,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_high_throughput_v19": {
        "intent": "high_throughput",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 625,
        "max_cost_per_query_usd": 0.105,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_strict_safety_v1": {
        "intent": "strict_safety",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 175,
        "max_cost_per_query_usd": 0.015,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_strict_safety_v2": {
        "intent": "strict_safety",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 200,
        "max_cost_per_query_usd": 0.02,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_strict_safety_v3": {
        "intent": "strict_safety",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 225,
        "max_cost_per_query_usd": 0.025,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_strict_safety_v4": {
        "intent": "strict_safety",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 250,
        "max_cost_per_query_usd": 0.03,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_strict_safety_v5": {
        "intent": "strict_safety",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 275,
        "max_cost_per_query_usd": 0.035,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_strict_safety_v6": {
        "intent": "strict_safety",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 300,
        "max_cost_per_query_usd": 0.04,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_strict_safety_v7": {
        "intent": "strict_safety",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 325,
        "max_cost_per_query_usd": 0.045000000000000005,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_strict_safety_v8": {
        "intent": "strict_safety",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 350,
        "max_cost_per_query_usd": 0.05,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_strict_safety_v9": {
        "intent": "strict_safety",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 375,
        "max_cost_per_query_usd": 0.055,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_strict_safety_v10": {
        "intent": "strict_safety",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 400,
        "max_cost_per_query_usd": 0.060000000000000005,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_strict_safety_v11": {
        "intent": "strict_safety",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 425,
        "max_cost_per_query_usd": 0.065,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_strict_safety_v12": {
        "intent": "strict_safety",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 450,
        "max_cost_per_query_usd": 0.06999999999999999,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_strict_safety_v13": {
        "intent": "strict_safety",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 475,
        "max_cost_per_query_usd": 0.075,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_strict_safety_v14": {
        "intent": "strict_safety",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 500,
        "max_cost_per_query_usd": 0.08,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_strict_safety_v15": {
        "intent": "strict_safety",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 525,
        "max_cost_per_query_usd": 0.08499999999999999,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_strict_safety_v16": {
        "intent": "strict_safety",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 550,
        "max_cost_per_query_usd": 0.09,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_strict_safety_v17": {
        "intent": "strict_safety",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 575,
        "max_cost_per_query_usd": 0.095,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_strict_safety_v18": {
        "intent": "strict_safety",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 600,
        "max_cost_per_query_usd": 0.09999999999999999,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
    "policy_strict_safety_v19": {
        "intent": "strict_safety",
        "primary_model": "gpt-4o",
        "fallback_models": ["claude-3-5-sonnet-20240620", "gemini-1.5-pro", "mock-gpt-4o"],
        "max_latency_budget_ms": 625,
        "max_cost_per_query_usd": 0.105,
        "circuit_breaker_error_threshold": 3,
        "circuit_breaker_recovery_seconds": 30.0,
        "enable_semantic_cache": True,
        "cache_similarity_threshold": 0.92,
        "retry_backoff_factor": 1.5
    },
}
